# Generated by Django 4.0.5 on 2022-06-22 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comTwitter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='name',
            new_name='author',
        ),
    ]
