# Generated by Django 4.0.5 on 2022-06-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comTwitter', '0002_alter_userprofile_hood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hood',
            field=models.CharField(default='Nairobi', max_length=255),
        ),
    ]
