# Generated by Django 4.0.5 on 2022-06-21 00:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comTwitter', '0003_alter_post_hood'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
