# Generated by Django 4.0.5 on 2022-06-21 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comTwitter', '0004_business_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='comTwitter.userprofile'),
        ),
    ]
