# Generated by Django 4.0.5 on 2022-06-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comTwitter', '0006_remove_business_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='description',
            field=models.TextField(default='', max_length=300),
        ),
    ]
